cart/urls.py
from django.urls import path

from . import views

app_name = "cart"

urlpatterns = [
    path("add/<str:product_id>/", views.add_to_cart, name="add_to_cart"),
    path("remove/<str:product_id>/", views.remove_from_cart, name="remove_from_cart"),
    path("decrease/<str:product_id>/", views.decrease_quantity, name="decrease_quantity"),
    path("view/", views.view_cart, name="view_cart"),
    path("clear/", views.clear_cart, name="clear_cart"),
    path("checkout/", views.checkout, name="checkout"),

]

config/urls.py
from allauth.account.views import ConfirmEmailView, EmailVerificationSentView
from dj_rest_auth.views import PasswordResetConfirmView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"),
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),

    path("", include("front.urls")),

    path("admin/", admin.site.urls),

    path("accounts/", include("allauth.urls")),
    path("accounts/", include("users.urls")),

    path("comments/", include("comment.urls")),
    path("cart/", include("cart.urls")),

    path("restaurant-dashboard/", include("restaurant.urls")),
    path("restaurant-dashboard/", include("food.urls")),
    path("restaurant-dashboard/", include("menu.urls")),
    path("api/restaurant-dashboard/", include("restaurant.api.urls")),
    path("api/restaurant-dashboard/", include("food.api.urls")),
    path("api/restaurant-dashboard/", include("menu.api.urls")),

    path("api/auth/", include("dj_rest_auth.urls")),

    path(
        "api/auth/registration/account-email-verification-sent/",
        EmailVerificationSentView.as_view(),
        name="account_email_verification_sent",
    ),
    path(
        "api/auth/password/reset/confirm/<str:uidb64>/<str:token>",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "api/auth/registration/account-confirm-email/<str:key>/",
        ConfirmEmailView.as_view(),
        name="account_confirm_email",
    ),

    path("api/auth/registration/", include("dj_rest_auth.registration.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

front/urls.py
from django.urls import path

from .views import detail_restaurant, home, list_restaurant

app_name = "front"

urlpatterns = [
    path("", home, name="home"),
    path("restaurants", list_restaurant, name="list_restaurant"),
    path("restaurants/detail/<str:restaurant_pk>", detail_restaurant, name="detail_restaurant"),
]

cart/models.py
from django.conf import settings
from django.db import models

from common.models import BaseModel
from food.models import Food


class Cart(BaseModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="cart")
    updated_at = None

    def __str__(self):
        return f"cart for {self.user.email}"


class CartItem(BaseModel):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="items")
    product = models.OneToOneField(Food, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.name}"

    def total_price(self):
        return self.quantity * self.product.price

cart/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from food.models import Food
from orders.models import Order, OrderItem, OrderStatus
from users.models import Address


# Utility function to calculate total price
def calculate_total(cart):
    return sum(item["total"] for item in cart.values())


@require_POST
def add_to_cart(request, product_id):
    product = get_object_or_404(Food, pk=product_id)
    cart = request.session.get("cart", {})

    if str(product_id) in cart:
        if product.count >= cart[str(product_id)]["quantity"]:
            # TODO: user will know the items count
            message = "cant add more than the Item quantity in the store"
            messages.success(request, message)
            return redirect(request.META.get("HTTP_REFERER", "/"))
        cart[str(product_id)]["quantity"] += 1
        cart[str(product_id)]["total"] = cart[str(product_id)]["quantity"] * cart[str(product_id)]["price"]
        message = "Item quantity updated"
        messages.success(request, message)
    else:
        cart[str(product_id)] = {
            "name": product.name,
            "quantity": 1,
            "pk": str(product_id),
            "price": float(product.price),
            "total": float(product.price),
        }

    request.session["cart"] = cart
    message = "Item added to the cart"
    messages.success(request, message)
    return redirect(request.META.get("HTTP_REFERER", "/"))


@require_POST
def remove_from_cart(request, product_id):
    cart = request.session.get("cart", {})

    if str(product_id) in cart:
        del cart[str(product_id)]
        request.session["cart"] = cart
        message = "Item removed from cart"
        messages.debug(request, message)

    return redirect(request.META.get("HTTP_REFERER", "/"))


@require_POST
def decrease_quantity(request, product_id):
    cart = request.session.get("cart", {})

    if str(product_id) in cart:
        if cart[str(product_id)]["quantity"] > 1:
            cart[str(product_id)]["quantity"] -= 1
            cart[str(product_id)]["total"] = cart[str(product_id)]["quantity"] * cart[str(product_id)]["price"]
            message = "Item quantity decreased"
            messages.debug(request, message)
        else:
            del cart[str(product_id)]
            message = "Item removed from cart"
            messages.debug(request, message)
    else:
        message = "Item not found in cart"
        messages.debug(request, message)

    request.session["cart"] = cart
    return redirect(request.META.get("HTTP_REFERER", "/"))


def view_cart(request):
    cart = request.session.get("cart", {})
    total_price = calculate_total(cart)

    return render(request, "cart/cart.html", {"cart": cart, "total_price": total_price})


@require_POST
def clear_cart(request):
    request.session["cart"] = {}
    message = "Cart cleared"
    messages.success(request, message)

    return render(request, "cart/cart.html", {"cart": {}, "total_price": 0})


@login_required(login_url=settings.LOGIN_URL)
def checkout(request):
    cart = request.session.get("cart", {})
    if cart == {}:
        messages.error(request, "cart is empty")
        return redirect("cart:view_cart")
    if not request.user.addresses.exists():
        messages.warning(request, "You need to add at least one address to receive the foods.")
        return redirect("users:create_address")
    if request.method == "POST":
        address_pk = request.POST.get("address", "")
        if not address_pk:
            messages.error(request, "Please select an address.")
            return redirect(request.META.get("HTTP_REFERER", "/"))

        address_object = get_object_or_404(Address, pk=address_pk)
        order, created = Order.objects.get_or_create(
            user=request.user,
            status=OrderStatus.PENDING,
            defaults={"shipping_address": address_object},
        )

        order_items = []
        for item_id, details in cart.items():
            food = get_object_or_404(Food, pk=item_id)
            quantity = details["quantity"]

            if quantity > food.count:
                messages.warning(request, f"We only have {food.count} of {food.name}. Please adjust your order.")
                return redirect(request.META.get("HTTP_REFERER", "/"))

            order_items.append(OrderItem(order=order, product=food, quantity=quantity, unit_price=food.price))

        OrderItem.objects.bulk_create(order_items)
        request.session["cart"] = {}

        messages.success(request, "Order created successfully!")
        order.status = OrderStatus.PROCESSING
        order.save()
        return redirect("cart:view_cart")

    total_price = calculate_total(cart)
    return render(request, "cart/checkout.html", {"cart": cart, "total_price": total_price})

cart/templates/cart/cart.html
{% extends "front_base.html" %}

{% block content %}
<div class="container my-4">
    <h2>Shopping Cart</h2>

    {% if cart %}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Food Item</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart.values %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>${{ item.price }}</td>
                <td>${{ item.total|floatformat:2 }}</td>
                <td>
                    <form class="display:inline;" action="{% url 'cart:add_to_cart' item.pk %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-success">+</button>
                    </form>
                    <form class="display:inline;" action="{% url 'cart:decrease_quantity' item.pk %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-warning">-</button>
                    </form>
                    <form class="display:inline;" action="{% url 'cart:remove_from_cart' item.pk %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-danger">remove</button>
                    </form>

                </td>
            </tr>
            {% endfor %}
        </tbody>
        
    </table>
    <div class="text-end">
        <h4>Total: ${{ total_price|floatformat:2 }}</h4>
        <a href="{% url 'cart:checkout' %}" class="btn btn-primary">Checkout</a>
        <a href="{% url 'cart:clear_cart' %}" class="btn btn-danger">Clear Cart</a>
    </div>
    {% else %}
    <p class="text-center">Your cart is empty. <a href="{% url 'front:list_restaurant' %}">Browse Restaurants</a></p>
    {% endif %}
</div>
{% endblock %}

cart/templates/cart/checkout.html
{% extends "front_base.html" %}
{% block title %}
    Checkout
{% endblock title %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Checkout</h1>

    <!-- Address Selection -->
    <form method="POST" action="{% url 'cart:checkout' %}">
        {% csrf_token %}
        <div class="mb-3">
            <label for="address" class="form-label">Select an Address:</label>
            <select class="form-select" id="address" name="address" required>
                {% for address in user.addresses.all %}
                    <option value="{{ address.pk }}">{{ address.title }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Cart Items -->
        <h2 class="mt-4">Your Cart</h2>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Food Item</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Total Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart.values %}
                    <tr>
                        <td>{{ item.name }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>${{ item.price }}</td>
                        <td>${{item.total }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4" class="text-center">Your cart is empty.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <h4>Total: ${{ total_price|floatformat:2 }}</h4>
        <!-- Submit Button -->
        <button type="submit" class="btn btn-primary mt-3">Place Order</button>
    </form>
{% endblock content %}